[2025-07-07T22:24:59.953] [INFO] proccess-worker - Job Queue workers is being started...
[2025-07-07T22:24:59.960] [INFO] add_task - auto sell job scheduler  running successfully
[2025-07-07T22:25:00.357] [INFO] app module - Server running on port 8100
[2025-07-07T22:25:01.347] [ERROR] redis_helper_service - redis error occured Error: getaddrinfo ENOTFOUND patricia_bot_redis_db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'patricia_bot_redis_db'
}
[2025-07-07T22:25:01.354] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:02.132] [ERROR] redis_helper_service - redis error occured Error: getaddrinfo ENOTFOUND patricia_bot_redis_db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'patricia_bot_redis_db'
}
[2025-07-07T22:25:02.144] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:02.349] [ERROR] redis_helper_service - redis error occured Error: getaddrinfo ENOTFOUND patricia_bot_redis_db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'patricia_bot_redis_db'
}
[2025-07-07T22:25:02.355] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:06.185] [ERROR] redis_helper_service - redis error occured Error: getaddrinfo ENOTFOUND patricia_bot_redis_db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'patricia_bot_redis_db'
}
[2025-07-07T22:25:06.187] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:06.399] [ERROR] redis_helper_service - redis error occured Error: getaddrinfo ENOTFOUND patricia_bot_redis_db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'patricia_bot_redis_db'
}
[2025-07-07T22:25:06.404] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:07.195] [ERROR] redis_helper_service - redis error occured Error: getaddrinfo ENOTFOUND patricia_bot_redis_db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'patricia_bot_redis_db'
}
[2025-07-07T22:25:07.206] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:07.403] [ERROR] redis_helper_service - redis error occured Error: getaddrinfo ENOTFOUND patricia_bot_redis_db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'patricia_bot_redis_db'
}
[2025-07-07T22:25:07.405] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:08.203] [ERROR] redis_helper_service - redis error occured Error: getaddrinfo ENOTFOUND patricia_bot_redis_db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'patricia_bot_redis_db'
}
[2025-07-07T22:25:08.207] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:08.420] [ERROR] redis_helper_service - redis error occured Error: getaddrinfo ENOTFOUND patricia_bot_redis_db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'patricia_bot_redis_db'
}
[2025-07-07T22:25:08.424] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:09.212] [ERROR] redis_helper_service - redis error occured Error: getaddrinfo ENOTFOUND patricia_bot_redis_db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'patricia_bot_redis_db'
}
[2025-07-07T22:25:09.215] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:09.443] [ERROR] redis_helper_service - redis error occured Error: getaddrinfo ENOTFOUND patricia_bot_redis_db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'patricia_bot_redis_db'
}
[2025-07-07T22:25:09.446] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:10.220] [ERROR] redis_helper_service - redis error occured Error: getaddrinfo ENOTFOUND patricia_bot_redis_db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'patricia_bot_redis_db'
}
[2025-07-07T22:25:10.229] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:10.414] [ERROR] seed module - error when seed wallet address Operation `users.findOne()` buffering timed out after 10000ms
[2025-07-07T22:25:11.416] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:11.420] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:12.219] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:12.222] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:12.432] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:12.435] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:16.247] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:16.250] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:16.476] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:16.482] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:17.307] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:17.313] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:17.469] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:17.478] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:18.265] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:18.271] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:18.496] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:18.501] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:19.281] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:19.284] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:19.503] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:19.513] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:20.292] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:20.295] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:21.543] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:21.547] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:22.335] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:22.340] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:22.547] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:22.560] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:26.363] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:26.366] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:26.589] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:26.592] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:27.434] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:27.439] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:27.598] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:27.604] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:28.378] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:28.383] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:28.623] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:28.627] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:29.397] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:29.400] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:29.619] [ERROR] redis_helper_service - redis error occured Error: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\user\Desktop\Tool\XAI__Backend\node_modules\ioredis\built\Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:602:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[2025-07-07T22:25:29.625] [INFO] redis_helper_service - redis reconnecting
[2025-07-07T22:25:30.117] [ERROR] app module -  🚀 Mongoose default connection is disconnected
